/* ══════════════════════════════════════════════════════════════
   seeds.js — GENERATED 2026-07-20 by test/audit-seeds.mjs, do not edit by hand.

   The "Surprise me" pool: 363 pre-resolved entities. Shipping
   QIDs (not bare strings) means the dice locks the exact intended entity
   instantly — no resolve-time latency, no same-named-EP surprises. Edit
   test/seed-names.mjs and re-run the audit to change the pool.
   ══════════════════════════════════════════════════════════════ */

export const SEEDS = [
  { id: 'Q7186', label: 'Marie Curie', description: 'Polish-French physicist and chemist (1867–1934)' },
  { id: 'Q7251', label: 'Alan Turing', description: 'English computer scientist (1912–1954)' },
  { id: 'Q935', label: 'Isaac Newton', description: 'English mathematician and physicist (1642–1727)' },
  { id: 'Q1035', label: 'Charles Darwin', description: 'English naturalist and biologist (1809–1882)' },
  { id: 'Q9036', label: 'Nikola Tesla', description: 'Serbian-American engineer and inventor (1856–1943)' },
  { id: 'Q7259', label: 'Ada Lovelace', description: 'English mathematician (1815–1852)' },
  { id: 'Q937', label: 'Albert Einstein', description: 'German-born theoretical physicist (1879–1955)' },
  { id: 'Q307', label: 'Galileo Galilei', description: 'Italian polymath (1564–1642)' },
  { id: 'Q7474', label: 'Rosalind Franklin', description: 'British chemist, biophysicist, and X-ray crystallographer (1920–1958)' },
  { id: 'Q11641', label: 'Grace Hopper', description: 'American computer scientist and United States Navy officer (1906–1992)' },
  { id: 'Q11740', label: 'Katherine Johnson', description: 'African-American mathematician' },
  { id: 'Q410', label: 'Carl Sagan', description: 'American astrophysicist, cosmologist and author (1934–1996)' },
  { id: 'Q184746', label: 'Jane Goodall', description: 'English primatologist and anthropologist (1934–2025)' },
  { id: 'Q529', label: 'Louis Pasteur', description: 'French chemist and microbiologist (1822-1895)' },
  { id: 'Q37970', label: 'Gregor Mendel', description: 'Moravian scientist and Augustinian friar (1822–1884)' },
  { id: 'Q7099', label: 'Emmy Noether', description: 'German Jewish mathematician (1882–1935)' },
  { id: 'Q83163', label: 'Srinivasa Ramanujan', description: 'Indian mathematician (1887–1920)' },
  { id: 'Q11903', label: 'Hypatia', description: 'Greek Neoplatonist philosopher' },
  { id: 'Q36620', label: 'Tycho Brahe', description: 'Danish astronomer and alchemist, 1546–1601' },
  { id: 'Q9106', label: 'Dmitri Mendeleev', description: 'Russian chemist (1834–1907)' },
  { id: 'Q8750', label: 'Michael Faraday', description: 'British scientist (1791–1867)' },
  { id: 'Q6694', label: 'Alexander von Humboldt', description: 'Prussian geographer, naturalist and explorer (1769-1859)' },
  { id: 'Q100948', label: 'Rachel Carson', description: 'American marine biologist and conservationist (1907–1964)' },
  { id: 'Q199654', label: 'Barbara McClintock', description: 'American scientist and cytogeneticist' },
  { id: 'Q762', label: 'Leonardo da Vinci', description: 'Italian Renaissance polymath (1452−1519)' },
  { id: 'Q8739', label: 'Archimedes', description: 'Greek mathematician and physicist (c. 287 – c. 212 BC)' },
  { id: 'Q868', label: 'Aristotle', description: '4th-century BCE Classical Greek philosopher and polymath' },
  { id: 'Q4604', label: 'Confucius', description: '5th-century BCE Chinese philosopher and politician' },
  { id: 'Q8011', label: 'Avicenna', description: 'Persian polymath, physician and philosopher (c. 980–1037)' },
  { id: 'Q9038', label: 'al-Khwarizmi', description: '9th-century Persian mathematician and astronomer' },
  { id: 'Q5582', label: 'Vincent van Gogh', description: 'Dutch painter (1853–1890)' },
  { id: 'Q5588', label: 'Frida Kahlo', description: 'Mexican painter (1907–1954)' },
  { id: 'Q5593', label: 'Pablo Picasso', description: 'Spanish painter and sculptor (1881–1973)' },
  { id: 'Q296', label: 'Claude Monet', description: 'French painter (1840–1926)' },
  { id: 'Q5577', label: 'Salvador Dalí', description: 'Spanish artist (1904–1989)' },
  { id: 'Q5586', label: 'Katsushika Hokusai', description: 'Japanese artist (1760-1849)' },
  { id: 'Q46408', label: 'Georgia O\'Keeffe', description: 'American modernist artist (1887–1986)' },
  { id: 'Q5598', label: 'Rembrandt', description: 'Dutch painter and printmaker (1606–1669)' },
  { id: 'Q5592', label: 'Michelangelo', description: 'Italian artist and architect (1475-1564)' },
  { id: 'Q61064', label: 'Wassily Kandinsky', description: 'avant-garde painter of Russian origin (1866-1944)' },
  { id: 'Q1339', label: 'Johann Sebastian Bach', description: 'German composer (1685–1750)' },
  { id: 'Q255', label: 'Ludwig van Beethoven', description: 'German composer (1770-1827)' },
  { id: 'Q254', label: 'Wolfgang Amadeus Mozart', description: 'Austrian composer of the Classical period (1756-1791)' },
  { id: 'Q7314', label: 'Igor Stravinsky', description: 'Russian, French, and American composer (1882–1971)' },
  { id: 'Q4030', label: 'Duke Ellington', description: 'American jazz pianist and composer (1899–1974)' },
  { id: 'Q93341', label: 'Miles Davis', description: 'American jazz trumpeter, bandleader, and composer (1926–1991)' },
  { id: 'Q1779', label: 'Louis Armstrong', description: 'American jazz musician, trumpeter and singer (1901–1971)' },
  { id: 'Q174957', label: 'Nina Simone', description: 'American singer, songwriter and pianist and civil rights activist (1933–2003)' },
  { id: 'Q125121', label: 'Aretha Franklin', description: 'American singer, songwriter, and pianist (1942–2018)' },
  { id: 'Q5383', label: 'David Bowie', description: 'English musician and actor (1947–2016)' },
  { id: 'Q15869', label: 'Freddie Mercury', description: 'British singer, songwriter and musician, frontman of the rock band Queen (1946–1991)' },
  { id: 'Q392', label: 'Bob Dylan', description: 'American singer-songwriter (born 1941)' },
  { id: 'Q42775', label: 'Johnny Cash', description: 'American country singer (1932–2003)' },
  { id: 'Q692', label: 'William Shakespeare', description: 'English playwright and poet (1564–1616)' },
  { id: 'Q36322', label: 'Jane Austen', description: 'English novelist (1775–1817)' },
  { id: 'Q7243', label: 'Leo Tolstoy', description: 'Russian author (1828–1910)' },
  { id: 'Q5878', label: 'Gabriel García Márquez', description: 'Colombian writer and Nobel laureate (1927–2014)' },
  { id: 'Q19526', label: 'Maya Angelou', description: 'American poet, author, and civil rights activist (1928–2014)' },
  { id: 'Q909', label: 'Jorge Luis Borges', description: 'Argentine writer, essayist, poet and translator (1899–1986)' },
  { id: 'Q40909', label: 'Virginia Woolf', description: 'English modernist writer (1882–1941)' },
  { id: 'Q905', label: 'Franz Kafka', description: 'Bohemian writer from Prague (1883–1924)' },
  { id: 'Q6691', label: 'Homer', description: 'reputed author of the Iliad and the Odyssey' },
  { id: 'Q72334', label: 'Toni Morrison', description: 'African American novelist, essayist, and academic (1931–2019)' },
  { id: 'Q55400', label: 'Hayao Miyazaki', description: 'Japanese animator, film director, and mangaka (born 1941)' },
  { id: 'Q7374', label: 'Alfred Hitchcock', description: 'British filmmaker (1899–1980)' },
  { id: 'Q882', label: 'Charlie Chaplin', description: 'English actor and filmmaker (1889–1977)' },
  { id: 'Q8006', label: 'Akira Kurosawa', description: 'Japanese filmmaker (1910–1998)' },
  { id: 'Q635', label: 'Cleopatra', description: 'queen of the Ptolemaic Kingdom of Egypt from 51 to 30 BCE' },
  { id: 'Q720', label: 'Genghis Khan', description: 'founder and first khan of the Mongol Empire (1162–1227)' },
  { id: 'Q1048', label: 'Julius Caesar', description: 'Roman general and dictator' },
  { id: 'Q517', label: 'Napoleon', description: 'French military leader, French Emperor 1804–1814 and again in 1815 (1769–1821)' },
  { id: 'Q9439', label: 'Queen Victoria', description: 'Queen of the United Kingdom from 1837 to 1901 (1819-1901)' },
  { id: 'Q8023', label: 'Nelson Mandela', description: 'President of South Africa and anti-apartheid activist (1918–2013)' },
  { id: 'Q1001', label: 'Mahatma Gandhi', description: 'Indian independence activist (1869–1948)' },
  { id: 'Q91', label: 'Abraham Lincoln', description: 'president of the United States from 1861 to 1865 (1809-1865)' },
  { id: 'Q36450', label: 'Catherine II of Russia', description: 'eighth Emperor of Russia, called the Great, r. 1762–1796 (lived 1729-1796)' },
  { id: 'Q8589', label: 'Ashoka', description: 'Mauryan emperor from 268 to 232 BCE' },
  { id: 'Q309333', label: 'Mansa Musa', description: '14th-century emperor (mansa) of the Mali Empire' },
  { id: 'Q7192', label: 'Qin Shi Huang', description: 'first emperor of Qin Dynasty' },
  { id: 'Q7207', label: 'Elizabeth I', description: 'Queen of England and Ireland from 1558 to 1603' },
  { id: 'Q37151', label: 'Sun Tzu', description: '6th century BCE Chinese general and military strategist' },
  { id: 'Q36456', label: 'Hannibal', description: 'Carthaginian general (247–183/181 BC)' },
  { id: 'Q7226', label: 'Joan of Arc', description: 'French folk heroine (1412–1431), military leader who crowned Charles VII and Roman Catholic saint, canonized 500 years after her death' },
  { id: 'Q43527', label: 'Sitting Bull', description: 'Hunkpapa Lakota medicine man and holy man (1831–1890)' },
  { id: 'Q102870', label: 'Harriet Tubman', description: 'African-American abolitionist (1822–1913)' },
  { id: 'Q215562', label: 'Frederick Douglass', description: 'African-American social reformer, writer, and abolitionist (c. 1818–1895)' },
  { id: 'Q957543', label: 'Ernest Shackleton', description: 'Anglo-Irish Antarctic explorer (1874–1922)' },
  { id: 'Q1496', label: 'Ferdinand Magellan', description: 'Portuguese explorer in the service of Spain' },
  { id: 'Q7333', label: 'Zheng He', description: 'Chinese mariner, explorer, and diplomat' },
  { id: 'Q3355', label: 'Amelia Earhart', description: 'American aviation pioneer and author (1897–1939)' },
  { id: 'Q926', label: 'Roald Amundsen', description: 'Norwegian explorer; first person to reach the South Pole (1872–1928)' },
  { id: 'Q7331', label: 'Ibn Battuta', description: '14th century Muslim Maghrebi scholar and explorer' },
  { id: 'Q6101', label: 'Marco Polo', description: 'Venetian explorer and merchant who travelled through Asia (1254–1324)' },
  { id: 'Q238960', label: 'Sacagawea', description: 'Native American woman & companion to Lewis and Clark at age 16' },
  { id: 'Q7327', label: 'Yuri Gagarin', description: 'Soviet pilot and cosmonaut, first human in space (1934–1968)' },
  { id: 'Q1615', label: 'Neil Armstrong', description: 'American astronaut and lunar explorer (1930–2012)' },
  { id: 'Q49285', label: 'Sally Ride', description: 'American astronaut and physicist (1951–2012)' },
  { id: 'Q207832', label: 'croissant', description: 'French pastry' },
  { id: 'Q46383', label: 'sushi', description: 'portioned prepared vinegared rice topped or rolled with other ingredients' },
  { id: 'Q177', label: 'pizza', description: 'Italian universal popular dish with a flat dough-based base and toppings' },
  { id: 'Q195', label: 'chocolate', description: 'nutritionally dense or sweet food product from the seed of Theobroma cacao - cocoa bean' },
  { id: 'Q8486', label: 'coffee', description: 'brewed beverage made from seeds of Coffea genus' },
  { id: 'Q6097', label: 'tea', description: 'brewed drink made from tea leaves' },
  { id: 'Q402563', label: 'maple syrup', description: 'syrup usually made from the xylem sap of sugar maple, red maple, or black maple trees' },
  { id: 'Q904889', label: 'sourdough', description: 'fermented dough' },
  { id: 'Q141898', label: 'Kimchi', description: 'Traditional Korean dish of fermented vegetables' },
  { id: 'Q241987', label: 'hummus', description: 'Levantine and Middle Eastern chickpea puree' },
  { id: 'Q212121', label: 'paella', description: 'rice dish from the Valencian Community, Spain' },
  { id: 'Q234646', label: 'ramen', description: 'Japanese noodle soup of Chinese origin' },
  { id: 'Q208172', label: 'baguette', description: 'elongated type of bread loaf' },
  { id: 'Q180289', label: 'espresso', description: 'strong type of coffee made using hot water under pressure' },
  { id: 'Q1362405', label: 'gelato', description: 'Italian style of ice cream' },
  { id: 'Q164606', label: 'curry', description: 'dish whose origins are in South and Southeast Asian cuisines' },
  { id: 'Q191655', label: 'taco', description: 'Mexican dish consisting of a corn or wheat tortilla folded or rolled around a filling, salsa and vegetabes' },
  { id: 'Q339836', label: 'dim sum', description: 'style of Chinese cuisine of bite-sized portions served in small steamer baskets or plates' },
  { id: 'Q160525', label: 'pretzel', description: 'German baked pastry shaped into a knot' },
  { id: 'Q272502', label: 'bagel', description: 'torus-shaped bread product' },
  { id: 'Q10987', label: 'honey', description: 'sweet food made by bees mostly using nectar from flowers' },
  { id: 'Q25434', label: 'saffron', description: 'spice derived from the flower of Crocus sativus' },
  { id: 'Q162044', label: 'Vanilla', description: 'genus of plants' },
  { id: 'Q28165', label: 'cinnamon', description: 'spice obtained from the inner bark of several tree species from the genus Cinnamomum' },
  { id: 'Q165199', label: 'chili pepper', description: 'fruit of plants from the genus Capsicum, members of the nightshade family, Solanaceae' },
  { id: 'Q170210', label: 'absinthe', description: 'alcoholic drink' },
  { id: 'Q134862', label: 'champagne', description: 'sparkling wine from Champagne, France' },
  { id: 'Q281', label: 'whisky', description: 'type of distilled alcoholic beverage made from fermented grain mash' },
  { id: 'Q170219', label: 'sake', description: 'alcoholic beverage of Japanese origin' },
  { id: 'Q169', label: 'mango', description: 'fruit of the mango tree' },
  { id: 'Q258896', label: 'banjo', description: 'stringed musical instrument' },
  { id: 'Q61285', label: 'ukulele', description: 'member of the guitar family' },
  { id: 'Q79838', label: 'accordion', description: 'musical instrument' },
  { id: 'Q51290', label: 'harmonica', description: 'free reed wind musical instrument' },
  { id: 'Q9798', label: 'saxophone', description: 'single-reed woodwind instrument' },
  { id: 'Q8355', label: 'violin', description: 'bowed string instrument' },
  { id: 'Q8371', label: 'cello', description: 'musical instrument' },
  { id: 'Q8347', label: 'bagpipe', description: 'reed wind instrument which in its commonest forms consists of a chanter and one or more drones, all supplied with air from the bag, which is compressed under the player’s arm to provide a constant pressure' },
  { id: 'Q229205', label: 'sitar', description: 'plucked stringed instrument used in Hindustani classical music' },
  { id: 'Q189388', label: 'didgeridoo', description: 'traditional Australian wind instrument' },
  { id: 'Q207691', label: 'theremin', description: 'electronic music instrument' },
  { id: 'Q81982', label: 'harpsichord', description: 'plucked-string keyboard instrument' },
  { id: 'Q220971', label: 'marimba', description: 'idiophone of Bantu origin consisting of wooden bars struck by mallets with resonator pipes below each bar; related to the West African balafon, and spread through the African diaspora to Central America and the Pacific coast of Colombia and Ecuador' },
  { id: 'Q189737', label: 'timpani', description: 'large percussion musical instrument which produces a definite pitch' },
  { id: 'Q281460', label: 'pipe organ', description: 'wind instrument that produces sound by driving pressurized air (called wind) through pipes selected via a keyboard' },
  { id: 'Q9764', label: 'flamenco', description: 'genre of Spanish music and dance' },
  { id: 'Q14390274', label: 'tango', description: 'music genre originating in Argentina and Uruguay' },
  { id: 'Q9794', label: 'reggae', description: 'music genre that originated in Jamaica in the late 1960s' },
  { id: 'Q9759', label: 'blues', description: 'vocal and instrumental music form' },
  { id: 'Q1344', label: 'opera', description: 'artform combining sung text and musical score in a theatrical setting' },
  { id: 'Q180268', label: 'gospel music', description: 'genre of music emphasizing Christian lyrics' },
  { id: 'Q213714', label: 'bluegrass', description: 'form of American roots music' },
  { id: 'Q208239', label: 'salsa', description: 'Latin American dance music genre' },
  { id: 'Q185676', label: 'fado', description: 'Portuguese music genre' },
  { id: 'Q194492', label: 'gamelan', description: 'style of traditional music originated in the island of Java in Indonesia' },
  { id: 'Q243', label: 'Eiffel Tower', description: 'tower located on the Champ de Mars in Paris, France' },
  { id: 'Q12501', label: 'Great Wall of China', description: 'series of fortifications built along the historical border of China' },
  { id: 'Q676203', label: 'Machu Picchu', description: '15th-century Inca citadel in the Peruvian Andes and UNESCO World Heritage Site' },
  { id: 'Q5788', label: 'Petra', description: 'ancient rock-cut historical city in Jordan' },
  { id: 'Q9141', label: 'Taj Mahal', description: 'marble mausoleum in Agra, India' },
  { id: 'Q10285', label: 'Colosseum', description: 'ancient Roman amphitheatre, a landmark of Rome, Italy' },
  { id: 'Q39671', label: 'Stonehenge', description: 'Neolithic henge monument in Amesbury, Wiltshire, England, UK' },
  { id: 'Q10288', label: 'Parthenon', description: 'former temple of Athena on the Athenian Acropolis, Greece' },
  { id: 'Q43473', label: 'Angkor Wat', description: 'Hindu-Buddhist temple complex in Cambodia' },
  { id: 'Q5859', label: 'Chichen Itza', description: 'pre-Columbian Maya city in Mexico' },
  { id: 'Q513', label: 'Mount Everest', description: 'Earth\'s highest mountain above sea level, located in the Mahalangur Himal sub-range of the Himalayas' },
  { id: 'Q34221', label: 'Niagara Falls', description: 'three waterfalls that straddle the international border between Canada and the United States' },
  { id: 'Q118841', label: 'Grand Canyon', description: 'steep-sided canyon carved by the Colorado River in Arizona, United States' },
  { id: 'Q6583', label: 'Sahara', description: 'desert on the African continent' },
  { id: 'Q51', label: 'Antarctica', description: 'terrestrial continent in the Southern Hemisphere' },
  { id: 'Q39231', label: 'Mount Fuji', description: 'volcano in Yamanashi and Shizuoka Prefectures, Japan' },
  { id: 'Q3783', label: 'Amazon', description: 'river in South America' },
  { id: 'Q3392', label: 'Nile', description: 'major river in northeastern Africa' },
  { id: 'Q23883', label: 'Dead Sea', description: 'lake with no outflow (sea) in Western Asia' },
  { id: 'Q5513', label: 'Lake Baikal', description: 'freshwater rift lake in southern Siberia, Russia; the greatest mountain lake in Asia and the most voluminous freshwater lake in the world' },
  { id: 'Q641', label: 'Venice', description: 'capital city of Veneto, Italy' },
  { id: 'Q406', label: 'Istanbul', description: 'largest city in Turkey' },
  { id: 'Q34600', label: 'Kyoto', description: 'city in the Kyōto Prefecture, Japan' },
  { id: 'Q101625', label: 'Marrakech', description: 'City in Marrakesh-Safi, Morocco' },
  { id: 'Q9427', label: 'Timbuktu', description: 'city in Mali' },
  { id: 'Q117188122', label: 'Galápagos Islands', description: 'UNESCO world heritage site in Ecuador' },
  { id: 'Q79934', label: 'U.S. Route 66', description: 'former U.S. Numbered Highway in the United States' },
  { id: 'Q58767', label: 'Trans-Siberian railway', description: 'railway line between Moscow, the Russian Far East and the Sea of Japan' },
  { id: 'Q7343', label: 'Great Barrier Reef', description: 'over 2300 km long coral reef off Australia\'s northeast coast, UNESCO World Heritage Site' },
  { id: 'Q14452', label: 'Easter Island', description: 'Polynesian island and special territory of Chile' },
  { id: 'Q15343', label: 'platypus', description: 'semi-aquatic egg-laying mammal endemic to Australia' },
  { id: 'Q40152', label: 'octopus', description: 'order of molluscs' },
  { id: 'Q22718', label: 'axolotl', description: 'species of salamander' },
  { id: 'Q159426', label: 'narwhal', description: 'medium-sized toothed whale that lives year-round in the Arctic' },
  { id: 'Q25397', label: 'pangolin', description: 'genus of pangolins' },
  { id: 'Q5194', label: 'tardigrade', description: 'phylum of animals' },
  { id: 'Q30178', label: 'jellyfish', description: 'soft-bodied, aquatic invertebrates' },
  { id: 'Q30034', label: 'honeybee', description: 'species of insect' },
  { id: 'Q212398', label: 'monarch butterfly', description: 'milkweed butterfly in the family Nymphalidae' },
  { id: 'Q201251', label: 'peacock', description: 'group of birds formed by the Indian peafowl, the green peafowl and the Congo peafowl' },
  { id: 'Q4504', label: 'Komodo dragon', description: 'species of reptile' },
  { id: 'Q42196', label: 'blue whale', description: 'species of marine mammal, largest living animal in the world' },
  { id: 'Q33602', label: 'Giant panda', description: 'species of mammal' },
  { id: 'Q37686', label: 'chameleon', description: 'family of reptiles' },
  { id: 'Q11709836', label: 'seahorse', description: 'type of fishes' },
  { id: 'Q25420', label: 'firefly', description: 'family of beetles' },
  { id: 'Q171446', label: 'coral', description: 'marine invertebrates of the class Anthozoa' },
  { id: 'Q83093', label: 'mushroom', description: 'spore-bearing fruiting body of a fungus' },
  { id: 'Q155825', label: 'Venus flytrap', description: 'carnivorous plant' },
  { id: 'Q149851', label: 'giant sequoia', description: 'species of large tree' },
  { id: 'Q670887', label: 'bamboo', description: 'subfamily of plants' },
  { id: 'Q171497', label: 'common sunflower', description: 'species of flowering plant in the family of Asteraceae' },
  { id: 'Q25308', label: 'Orchid', description: 'family of plants' },
  { id: 'Q131825', label: 'baobab', description: 'species of plant' },
  { id: 'Q16528', label: 'lotus', description: 'species of plant' },
  { id: 'Q131219', label: 'common dandelion', description: 'plant species' },
  { id: 'Q1055316', label: 'kelp', description: 'large brown seaweeds in the order Laminariales' },
  { id: 'Q43142', label: 'lichen', description: 'composite organism that arises from algae or cyanobacteria living among filaments of multiple fungi in a symbiotic relationship' },
  { id: 'Q14560', label: 'cactus', description: 'family of mostly succulent plants, adapted to dry environments' },
  { id: 'Q46335', label: 'typewriter', description: 'mechanical or electromechanical machine for typing characters' },
  { id: 'Q19806', label: 'bubble wrap', description: 'pliable transparent plastic material' },
  { id: 'Q39715', label: 'lighthouse', description: 'structure designed to emit light to aid navigation' },
  { id: 'Q34735', label: 'compass', description: 'instrument that indicated direction relative to the magnetic field of the Earth' },
  { id: 'Q4213', label: 'telescope', description: 'instrument that aids in the observation of remote objects' },
  { id: 'Q196538', label: 'microscope', description: 'instrument used to see objects that are too small for the naked eye' },
  { id: 'Q144334', label: 'printing press', description: 'device for evenly printing ink onto a print medium' },
  { id: 'Q446', label: 'wheel', description: 'circular item that rotates about an axial bearing; one of the six simple machines' },
  { id: 'Q12190', label: 'penicillin', description: 'group of antibiotics derived from Penicillium fungi' },
  { id: 'Q47616', label: 'incandescent light bulb', description: 'electric light bulb with a resistively heated wire filament' },
  { id: 'Q11035', label: 'telephone', description: 'telecommunications device that permits two or more users to conduct a conversation' },
  { id: 'Q11442', label: 'bicycle', description: 'pedal-driven two-wheel vehicle' },
  { id: 'Q15328', label: 'camera', description: 'optical device for recording or transmitting photographic images or videos' },
  { id: 'Q376', label: 'clock', description: 'instrument that measures the passage of time' },
  { id: 'Q12861', label: 'gunpowder', description: 'explosive most commonly used as propellant in firearms' },
  { id: 'Q11472', label: 'paper', description: 'thin, flexible material mainly used for writing upon, printing upon, drawing or for packaging' },
  { id: 'Q34396', label: 'soap', description: 'salt of fatty acids, used for washing and cleaning' },
  { id: 'Q101761', label: 'zipper', description: 'device for fastening the edges of an opening of fabric or other flexible material' },
  { id: 'Q15411420', label: 'hook and loop fastener', description: 'system for repeated quick opening and closing between two (usually flexible) surfaces' },
  { id: 'Q41607', label: 'umbrella', description: 'canopy designed to protect against inclement weather, particularly rain and sun' },
  { id: 'Q35197', label: 'mirror', description: 'surface, typically glass coated with a metal amalgam, which reflects a clear image' },
  { id: 'Q40847', label: 'scissors', description: 'hand-operated cutting instrument' },
  { id: 'Q14674', label: 'pencil', description: 'writing implement' },
  { id: 'Q80728', label: 'dynamite', description: 'explosive preparation of stabilized nitroglycerin' },
  { id: 'Q49013', label: 'sewing machine', description: 'a machine used to sew fabric and materials together with thread' },
  { id: 'Q37828', label: 'refrigerator', description: 'household or industrial appliance for preserving food at a low temperature' },
  { id: 'Q482816', label: 'parachute', description: 'device used to slow the motion of an object through an atmosphere' },
  { id: 'Q79897', label: 'Morse code', description: 'communication code with signals representing letters, punctuation marks and numbers' },
  { id: 'Q79757', label: 'barometer', description: 'scientific instrument used to measure atmospheric pressure' },
  { id: 'Q160567', label: 'seismometer', description: 'instrument that records seismic waves by measuring ground motions, caused by earthquakes, volcanic eruptions, and explosions' },
  { id: 'Q6534', label: 'French Revolution', description: 'revolution in France from 1789 to 1799' },
  { id: 'Q4692', label: 'Renaissance', description: 'cultural movement that spanned the period roughly from the 14th to the 17th century' },
  { id: 'Q36288', label: 'Silk Road', description: 'trade routes through Asia connecting China to the Mediterranean Sea' },
  { id: 'Q2269', label: 'Industrial Revolution', description: 'transition to new manufacturing processes in Europe and the United States, in the 18th-19th centuries' },
  { id: 'Q43653', label: 'Apollo 11', description: 'first Moon landing and fifth crewed flight of the United States Apollo program' },
  { id: 'Q8683', label: 'Cold War', description: '1947–1991 tension between the Soviet Union and the United States and their respective allies' },
  { id: 'Q17550', label: 'the California Gold Rush', description: 'gold rush from C.E.1848 until 1855 in California' },
  { id: 'Q42005', label: 'Black Death', description: '1346–1353 pandemic in Eurasia and North Africa' },
  { id: 'Q49367', label: 'ice age', description: 'period of long-term reduction in temperature of Earth\'s surface and atmosphere' },
  { id: 'Q323', label: 'Big Bang', description: 'hypothetical begin of the Universe through expansion out of an infinitely small and infinitely dense state' },
  { id: 'Q69163529', label: 'fall of the Berlin Wall', description: 'historical event in November 1989 where the Berlin Wall was opened and demolished' },
  { id: 'Q1932', label: 'space race', description: 'competition to explore space between USA and USSR' },
  { id: 'Q46388', label: 'prohibition', description: 'outlawing of the consumption, sale, production, etc. of alcohol' },
  { id: 'Q12539', label: 'Age of Enlightenment', description: 'period of European history and cultural movement of the 17th and 18th centuries' },
  { id: 'Q12560', label: 'Ottoman Empire', description: 'multiethnic empire with the monarchs from the Ottoman dynasty (1299–1922)' },
  { id: 'Q2277', label: 'Roman Empire', description: 'period of ancient Rome following the Republic' },
  { id: 'Q12544', label: 'Byzantine Empire', description: 'Roman Empire during Late Antiquity and the Middle Ages' },
  { id: 'Q9903', label: 'Ming dynasty', description: 'imperial dynasty of China from 1368 to 1644' },
  { id: 'Q2608489', label: 'Aztec Empire', description: 'former Mesoamerican empire' },
  { id: 'Q28573', label: 'Inca Empire', description: '1438–1533 empire in South America' },
  { id: 'Q45585', label: 'The Starry Night', description: 'painting by Vincent van Gogh' },
  { id: 'Q12418', label: 'Mona Lisa', description: 'oil painting by Leonardo da Vinci in the Louvre, Paris' },
  { id: 'Q471379', label: 'The Scream', description: 'group of paintings by Edvard Munch' },
  { id: 'Q48584', label: 'Rosetta Stone', description: 'ancient Egyptian stele with inscriptions in three writing systems' },
  { id: 'Q151952', label: 'Venus de Milo', description: 'ancient Greek marble statue of a woman' },
  { id: 'Q47672', label: 'Terracotta Army', description: 'collection of ancient Chinese military statues' },
  { id: 'Q4653', label: 'Sherlock Holmes', description: 'fictional character (consulting detective) created by Sir Arthur Conan Doyle' },
  { id: 'Q480', label: 'Don Quixote', description: '1605 and 1615 novel by Miguel de Cervantes' },
  { id: 'Q41542', label: 'Dracula', description: '1897 novel by Bram Stoker' },
  { id: 'Q2021531', label: 'Frankenstein', description: '1818 fictional character by Mary Shelley' },
  { id: 'Q174596', label: 'Moby-Dick', description: 'novel by Herman Melville' },
  { id: 'Q35160', label: 'The Odyssey', description: 'epic poem attributed to Homer' },
  { id: 'Q41567', label: 'Hamlet', description: 'tragedy by William Shakespeare' },
  { id: 'Q92640', label: 'Alice\'s Adventures in Wonderland', description: '1865 children\'s novel by Lewis Carroll' },
  { id: 'Q8065468', label: 'Pinocchio', description: '1883 novel by Carlo Collodi' },
  { id: 'Q45792', label: 'King Arthur', description: 'legendary British leader of the late 5th and early 6th centuries' },
  { id: 'Q122634', label: 'Robin Hood', description: 'heroic outlaw in English folklore, a highly skilled archer and swordsman' },
  { id: 'Q6567', label: 'Godzilla', description: 'fictional giant monster' },
  { id: 'Q844', label: 'James Bond', description: 'series of books about a British spy' },
  { id: 'Q718', label: 'chess', description: 'strategy board game' },
  { id: 'Q11413', label: 'go', description: 'board game for two players that originated in China more than 2,500 years ago' },
  { id: 'Q80131', label: 'poker', description: 'family of card games' },
  { id: 'Q12263', label: 'mahjong', description: 'game' },
  { id: 'Q83357', label: 'origami', description: 'traditional Japanese art of paper folding' },
  { id: 'Q83207', label: 'crossword', description: 'word puzzle game' },
  { id: 'Q47043', label: 'Rubik\'s Cube', description: '3-D combination puzzle with many different permutations' },
  { id: 'Q653928', label: 'pinball', description: 'type of arcade game' },
  { id: 'Q204832', label: 'roller coaster', description: 'type of amusement ride found at amusement parks and carnivals' },
  { id: 'Q202570', label: 'Ferris wheel', description: 'amusement ride' },
  { id: 'Q194326', label: 'juggling', description: 'circus skill' },
  { id: 'Q583269', label: 'tarot', description: 'set of cards used for games or divination' },
  { id: 'Q32907', label: 'dominoes', description: 'game played with rectangular tiles' },
  { id: 'Q11411', label: 'backgammon', description: 'one of the oldest board games for two players' },
  { id: 'Q183621', label: 'yo-yo', description: 'toy' },
  { id: 'Q170484', label: 'Lego', description: 'construction toy' },
  { id: 'Q181008', label: 'jigsaw puzzle', description: 'type of tiling puzzle' },
  { id: 'Q71910', label: 'Tetris', description: '1984 tile-matching puzzle video game series' },
  { id: 'Q173626', label: 'Pac-Man', description: '1980 arcade game developed by Namco' },
  { id: 'Q589', label: 'black hole', description: 'astronomical object so massive, that anything falling into it, including light, cannot escape its gravity' },
  { id: 'Q193', label: 'Saturn', description: 'sixth planet in the Solar System, with a ring system mainly composed of ice particles' },
  { id: 'Q405', label: 'Moon', description: 'Earth\'s only natural satellite' },
  { id: 'Q525', label: 'Sun', description: 'star at the centre of the Solar System' },
  { id: 'Q23054', label: 'Halley’s Comet', description: 'short-period comet visible from Earth every 75–76 years' },
  { id: 'Q40609', label: 'the aurora', description: 'natural light display that occurs in the sky, primarily at high latitudes (near the Arctic and Antarctic on Earth) or even on other planets' },
  { id: 'Q48469', label: 'Voyager 1', description: 'space probe launched by NASA to study the outer Solar System, furthest spacecraft from Earth' },
  { id: 'Q2513', label: 'Hubble Space Telescope', description: 'NASA and ESA space telescope (launched 1990)' },
  { id: 'Q25271', label: 'International Space Station', description: 'modular space station in low Earth orbit' },
  { id: 'Q7430', label: 'DNA', description: 'molecule that encodes the genetic instructions used in the development and functioning of all known living organisms and many viruses' },
  { id: 'Q9121', label: 'the atom', description: 'smallest unit of a chemical element' },
  { id: 'Q11412', label: 'gravity', description: 'fundamental interaction affecting all matter' },
  { id: 'Q12725', label: 'electricity', description: 'physical phenomena associated with the presence and flow of electric charge' },
  { id: 'Q1052', label: 'the rainbow', description: 'meteorological phenomenon caused by reflection, refraction and dispersion of light in water droplets' },
  { id: 'Q33741', label: 'lightning', description: 'weather phenomenon involving electrostatic discharge' },
  { id: 'Q8072', label: 'volcano', description: 'natural, surface vent or fissure usually in a mountainous form' },
  { id: 'Q7944', label: 'earthquake', description: 'result of a sudden release of energy in the Earth\'s crust that creates seismic waves' },
  { id: 'Q35666', label: 'glacier', description: 'large persistent body of ice' },
  { id: 'Q3937', label: 'supernova', description: 'star exploding at the end of its stellar lifespan' },
  { id: 'Q321', label: 'Milky Way', description: 'galaxy containing our Solar System' },
  { id: 'Q3559', label: 'comet', description: 'icy small astronomical object' },
  { id: 'Q43010', label: 'quartz', description: 'mineral made of silicon and oxygen' },
  { id: 'Q5283', label: 'diamond', description: 'allotrope of carbon often used as a gemstone and an abrasive' },
  { id: 'Q25381', label: 'amber', description: 'fossilized tree resin' },
  { id: 'Q60186', label: 'meteorite', description: 'piece of solid matter from outer space that has impacted the Earth' },
  { id: 'Q483444', label: 'kimono', description: 'traditional Japanese garment' },
  { id: 'Q216797', label: 'tartan', description: 'Scottish cloth pattern, said (often erroneously) to represent a clan, region, or other group of people' },
  { id: 'Q37681', label: 'silk', description: 'fine, lustrous, natural fiber produced by the larvae of various silk moths, especially the species Bombyx mori' },
  { id: 'Q83363', label: 'jeans', description: 'trousers often made from denim or dungaree cloth' },
  { id: 'Q231250', label: 'lace', description: 'openwork fabric, patterned with open holes in the work, made by machine or by hand' },
  { id: 'Q11642', label: 'pottery', description: 'craft of making objects from clay' },
  { id: 'Q12681', label: 'calligraphy', description: 'visual art related to writing' },
  { id: 'Q1473346', label: 'stained glass', description: 'colored glass used as an art material' },
  { id: 'Q133067', label: 'mosaic', description: 'image or writing made from an assemblage of small pieces of colored glass, stone, or other materials' },
  { id: 'Q72941682', label: 'tattoo', description: 'image created by ink placed in human skin, permanently or semi-permanently' },
  { id: 'Q131746', label: 'perfume', description: 'a substance, extract, or preparation for diffusing or imparting an agreeable or attractive smell, especially a fluid such as alcohol containing essential oils and/or aroma compounds' },
  { id: 'Q38720', label: 'windmill', description: 'machine that converts the energy of wind into rotational energy by means of adjustable sails' },
  { id: 'Q80793', label: 'sundial', description: 'device that tells the time of day by the apparent position of the Sun in the sky' },
  { id: 'Q12806', label: 'abacus', description: 'calculating tool' },
  { id: 'Q173056', label: 'loom', description: 'device for weaving textiles' },
  { id: 'Q635427', label: 'batik', description: 'Indonesian cloth dyeing technique originating from Java' },
  { id: 'Q1064538', label: 'the quilt', description: 'bedcover made of multiple layers of fabric sewn together, usually stitched in decorative patterns' },
  { id: 'Q125576', label: 'papyrus', description: 'writing and painting material' },
  { id: 'Q179904', label: 'the hourglass', description: 'device to measure the passage of time' },
  { id: 'Q168432', label: 'the anchor', description: 'mooring device' },
  { id: 'Q83809', label: 'a totem pole', description: 'type of monumental carving by indigenous peoples of the Pacific Northwest' },
  { id: 'Q1032349', label: 'a crystal ball', description: 'crystal or glass ball and common fortune telling object' },
  { id: 'Q7559', label: 'dragon', description: 'legendary winged, fire-breathing reptile' },
  { id: 'Q7246', label: 'unicorn', description: 'legendary animal, that looks like a horse or a goat with a horn on the forehead' },
  { id: 'Q182559', label: 'mermaid', description: 'legendary aquatic creature with the upper body of a female human and the fin of a fish' },
  { id: 'Q48963', label: 'the labyrinth', description: 'usually a system of narrow corridors designed to confuse those who enter and make finding a correct path difficult' },
  { id: 'Q151480', label: 'the sphinx', description: 'mythological creature with the head of a human and the body of a lion' },
  { id: 'Q215085', label: 'the golem', description: 'animated anthropomorphic being in Jewish folklore' },
  { id: 'Q193165', label: 'the kraken', description: 'legendary sea monster of large proportions' },
  { id: 'Q25373', label: 'Atlantis', description: 'mythological large island in Plato\'s dialogues' },
  { id: 'Q49658', label: 'Loch Ness Monster', description: 'lake monster of Scottish folklore' },
  { id: 'Q44810', label: 'Bigfoot', description: 'large and hairy ape-like mythical creature purported to inhabit forests in North America' },
  { id: 'Q129628', label: 'Yeti', description: 'ape-like creature purported to inhabit the Himalayan mountain range in Asia' },
  { id: 'Q46721', label: 'vampire', description: 'mythological or folkloric creature' },
  { id: 'Q9410', label: 'werewolf', description: 'mythological human with the ability to shapeshift into a wolf or an anthropomorphic wolf-like creature' },
  { id: 'Q45529', label: 'ghost', description: 'soul or spirit of a dead person or animal that can appear to the living' },
  { id: 'Q39689', label: 'alchemy', description: 'ensemble of protoscientific, philosophic and esoteric speculations and experiences, which investigate the transmutation of matter and the functioning of the cosmos' },
  { id: 'Q640047', label: 'compass rose', description: 'figure on a compass, map, nautical chart, or monument used to display the orientation of the cardinal directions' },
  { id: 'Q756314', label: 'four-leaf clover', description: 'a variation/mutation of the common clover, rare and said to bring good luck' },
];
